workflows:
  release-build:
    name: Debug Build with Cache Clear
    environment:
      flutter: stable
    scripts:
      - rm -rf ~/.gradle/caches/
      - flutter clean
      - flutter build apk --debug 2>&1 | tee build.log
      - tail -80 build.log
    artifacts:
      - build.log
      - build/app/outputs/flutter-apk/app-debug.apk
