workflows:
  release-build:
    name: Release Build
    environment:
      flutter: stable
    scripts:
      - rm -rf ~/.gradle/caches/
      - flutter clean
      - flutter build apk --release || true
      - find build -name "*.apk" -exec cp {} build/app/outputs/flutter-apk/app-release.apk \;
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
